fix weather i3block

diff --git a/.config/i3/scripts/openweather-city b/.config/i3/scripts/openweather-city
--- a/.config/i3/scripts/openweather-city
+++ b/.config/i3/scripts/openweather-city
@@ -1,44 +1,46 @@
 #!/usr/bin/env bash
 
-command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.
-Aborting."; exit 1; }
-command -v wget >/dev/null 2>&1 || { echo >&2 "Program 'wget' required but is not installed.
-Aborting."; exit 1; }
+# command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.
+# Aborting."; exit 1; }
+# command -v wget >/dev/null 2>&1 || { echo >&2 "Program 'wget' required but is not installed.
+# Aborting."; exit 1; }
 
-# To use this script you need to create an API key here https://home.openweathermap.org
-# You need to put your Open Weather APIKEY here:
-APIKEY="da8e423a0090d2da2834266f3d0848dd"
-# find your City ID here: https://openweathermap.org/
-# search for your city and copy the ID from the URL inside the browser.
-CITY_ID="3453643"
-URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&units=metric&APPID=${APIKEY}"
+# # To use this script you need to create an API key here https://home.openweathermap.org
+# # You need to put your Open Weather APIKEY here:
+# APIKEY="917737ed0055c2a46b668fd269a8dc20"
+# # find your City ID here: https://openweathermap.org/
+# # search for your city and copy the ID from the URL inside the browser.
+# CITY_ID="3453643"
+# # URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&units=metric&APPID=${APIKEY}"
+# URL="http://api.weatherapi.com/v1/current.json?key=a547a1e984054494bfe20806240904&q=Piracicaba&aqi=no"
 
-WEATHER_RESPONSE=$(wget -qO- "${URL}")
+# WEATHER_RESPONSE=$(wget -qO- "${URL}")
 
-WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.weather[0].main' | sed 's/"//g')
-WEATHER_TEMP=$(echo $WEATHER_RESPONSE | jq '.main.temp')
-WIND_DIR=$( echo "$WEATHER_RESPONSE" | jq '.wind.deg')
-WIND_SPEED=$( echo "$WEATHER_RESPONSE" | jq '.wind.speed')
+# WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.current.condition.text' | sed 's/"//g')
+# WEATHER_TEMP=$(echo $WEATHER_RESPONSE | jq '.current.temp_c' )
+# WIND_DIR=$( echo "$WEATHER_RESPONSE" | jq '.current.wind_dir')
+# WIND_SPEED=$( echo "$WEATHER_RESPONSE" | jq '.current.wind_kph')
 
-WIND_SPEED=$(awk "BEGIN {print 60*60*$WIND_SPEED/1000}")
-WIND_DIR=$(awk "BEGIN {print int(($WIND_DIR % 360)/22.5)}")
-DIR_ARRAY=( N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N )
-WIND_DIR=${DIR_ARRAY[WIND_DIR]}
+# WIND_SPEED=$(awk "BEGIN {print 60*60*$WIND_SPEED/1000}")
+# WIND_DIR=$(awk "BEGIN {print int(($WIND_DIR % 360)/22.5)}")
+# DIR_ARRAY=( N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N )
+# WIND_DIR=${DIR_ARRAY[WIND_DIR]}
 
-case $WEATHER_CONDITION in
-  'Clouds')
-    WEATHER_ICON=""
-    ;;
-  'Rain')
-    WEATHER_ICON=""
-    ;;
-  'Snow')
-    WEATHER_ICON=""
-    ;;
-  *)
-    WEATHER_ICON=""
-    ;;
-esac
+# case $WEATHER_CONDITION in
+#   'Clouds')
+#     WEATHER_ICON=""
+#     ;;
+#   'Rain')
+#     WEATHER_ICON=""
+#     ;;
+#   'Snow')
+#     WEATHER_ICON=""
+#     ;;
+#   *)
+#     WEATHER_ICON=""
+#     ;;
+# esac
 
 # echo "${WEATHER_ICON} ${WEATHER_TEMP}°C    煮 ${WIND_SPEED}km/h"
-echo "${WEATHER_ICON} ${WEATHER_TEMP}°C"
+# echo "${WEATHER_ICON} ${WEATHER_TEMP}°C"
+echo "EITA"
